import type { Project } from "@/types/portfolio";

export const projects: Project[] = [
  {
    id: "api-lens",
    name: "API Lens",
    detailTitle: "API Lens - AI-Powered REST API Quality Analyzer",
    year: "2026",
    subtitle: "AI-Powered REST API Quality Analyzer",
    role: "Founder & Full-Stack Developer",
    description:
      "API Lens is a platform designed to analyze REST APIs and automatically detect API design issues, code quality problems, and API smells.",
    features: [
      "API Quality Scoring",
      "API Smell Detection",
      "Rule Engine Validation",
      "AI Recommendations",
      "AST Source Code Analysis",
      "OpenAPI Support",
    ],
    techStack: ["React", "Node.js", "Express.js", "MongoDB", "OpenAPI", "GitHub Integration"],
    imageSrc: "/apilens.png",
    images: [
      "/apilens/apilens1.png",
      "/apilens/apilens2.png",
      "/apilens/apilens3.png",
      "/apilens/apilens4.png",
      "/apilens/apilens5.png",
    ],
    liveDemoUrl: "https://apilens.com",
    githubUrl: "https://github.com/mit-suu/api-lens",
    featured: true,
  },
  {
    id: "kix-shop",
    name: "KIX Shop",
    detailTitle: "KIX Shop - Sneaker E-Commerce Platform",
    year: "2025",
    subtitle: "Sneaker E-Commerce Platform",
    role: "Team Leader & Backend Developer",
    description:
      "A modern e-commerce platform focused on sneaker retail management with authentication, product management, cart system, order processing, and inventory management.",
    features: ["Authentication", "Product Management", "Cart System", "Order Processing", "Inventory Management"],
    techStack: ["MERN Stack", "Cloudinary", "Azure", "GitHub Actions", "Vercel"],
    imageSrc: "/kix.png",
    images: [
      "/kix/kix1.png",
      "/kix/kix2.png",
      "/kix/kix3.png",
      "/kix/kix4.png",
      "/kix/kix5.png",
    ],
    liveDemoUrl: "https://kixshop.com",
    githubUrl: "https://github.com/mit-suu/kix-shop",
    featured: false,
  },
  {
    id: "hostelink",
    name: "Hostelink",
    detailTitle: "Hostelink - Hotel Booking Management System",
    year: "2024",
    subtitle: "Hotel Booking Management System",
    role: "Backend Developer",
    description: "A hotel reservation and management platform developed as an academic project.",
    features: ["Reservation Management", "Booking Workflows", "Backend API Design"],
    techStack: ["Node.js", "Express.js", "MongoDB"],
    imageSrc: "/hostelink.png",
    images: [
      "/hostelink/hostelink1.png",
      "/hostelink/hostelink2.png",
      "/hostelink/hostelink3.png",
      "/hostelink/hostelink4.png",
      "/hostelink/hostelink5.png",
    ],
    liveDemoUrl: "https://hostelink.com",
    githubUrl: "https://github.com/mit-suu/hostelink",
    featured: false,
  },
];
